### ISSUE TITLE
the linux build provided doesnt run on arm64

### ISSUE THREAD

**Issue by xxpawman420xx** [dogkisser/goonto#18]
the build provided in assets doesn't work on ubuntu 64-bit 24.04 running on arm64 and compiling the source throws soo many errors i don't know where to start, here's some of my terminal output from trying to build it - cant even post the whole output because it exceeds githubs 65k character limit, the given build command also didn't work and after some googling this modified command was needed to get anywhere with it, maybe provide an arm compatible build if you do indeed support arm or some better build instructions - all requirements listed in your yaml file was installed, all the x11 libs and cmake
---
cargo +nightly build --release --features=fltk/fltk-bundled
   Compiling goonto v0.1.0 (/home/blake/Downloads/goonto)
error: linking with `cc` failed: exit status: 1
  |
  
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)

error: could not compile `goonto` (bin "goonto") due to 1 previous error

**Comment by xxpawman420xx** [comment]
then this is the output from running the linux build 
blake@blake-desktop:~/Downloads$ ./goonto-linux-x11 
bash: ./goonto-linux-x11: cannot execute binary file: Exec format error

**Comment by xxpawman420xx** [comment]
and this is from running the build command listed 
cargo build --release

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:3:12
  |
3 | #![feature(panic_update_hook)]
  |            ^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `goonto` (bin "goonto") due to 1 previous error

**Comment by kink-kat** [comment]
If you could paste the big error into a [GitHub Gist](https://gist.github.com/) and share that here, it'd be appreciated and make it easier to figure out what's going on.

> error[E0554]: #![feature] may not be used on the stable release channel

Yeah, it seems the documentation is inaccurate, as you do currently need to use the nightly compiler to build it.

I'm not sure the current `panic_update_hook` feature usage is entirely needed at the moment; it seems the behavior can be emulated if a panic hook isn't being updated in other threads at the same time, which I don't think is applicable here.

**Comment by dogkisser** [comment]
Yea I don't think the code uses panic_update_hook anymore, that's left over from testing. I'll remove it

**Comment by dogkisser** [comment]
Apparently `update_hook` can be replaced with `take_hook` and `set_hook` on stable yeah. i'd accept a PR for that but personally I'd just suggest switching to nightly haha. and to my credit, the docs don't say to use stable.

None of the code in Goonto is architecture dependent and apparently fltk-rs builds on arm64, so I don't know what's causing build issues. I'd need the rest of the build log to take a guess.

> then this is the output from running the linux build
> blake@blake-desktop:~/Downloads$ ./goonto-linux-x11
> bash: ./goonto-linux-x11: cannot execute binary file: Exec format error

Yeah it's an x86_64 binary

**Comment by xxpawman420xx** [comment]
Thanks for your replies and patience, here's the gist file with a complete output of my terminal so you can see what directory I was in when building and what command I ran and the resulting error - it might easily be a case of I'm too dumb to do this xD in my defense I've been using Linux for all of 3 days now as my daily and goodness is it a steep learning curve  haha (and when i wrote my original issue i was probably far too frustrated with everything, didn't mean it to sound that brutal)
---
https://gist.github.com/xxpawman420xx/d292cf5ea1a7b17b3b81706a5a0803c3

**Comment by dogkisser** [comment]
You're missing `libcairo2-dev` and `libpango1.0-dev`

```
undefined reference to `pango_context_set_font_description'
undefined reference to `cairo_image_surface_create'
```

**Comment by xxpawman420xx** [comment]
already had them both installed

blake@blake-desktop:~/Desktop$ sudo apt-get install libcairo2-dev
[sudo] password for blake: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcairo2-dev is already the newest version (1.18.0-3build1).
libcairo2-dev set to manually installed.
0 to upgrade, 0 to newly install, 0 to remove and 1 not to upgrade.
blake@blake-desktop:~/Desktop$ sudo apt-get install libpango1.0-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libpango1.0-dev is already the newest version (1.52.1+ds-1build1).
0 to upgrade, 0 to newly install, 0 to remove and 1 not to upgrade.

**Comment by dogkisser** [comment]
hmm

**Comment by dogkisser** [comment]
hey sorry i kinda forgot about this, yeah i'm not sure what's up. the linker command doesn't even appear to *try* linking pango/cairo. very very preemptively i think this might be a bug in fltk-rs/a dependent

**Comment by dogkisser** [comment]
i think commits i made on codeberg fixed this https://codeberg.org/rocketcookie/goonto
